apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: kyverno-policies
    version: 3.6.3
    repo: https://kyverno.github.io/kyverno
    releaseName: kyverno-policies
    namespace: kyverno
    valuesFile: values.yaml