apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: headlamp
    repo: https://kubernetes-sigs.github.io/headlamp
    version: 0.40.0
    releaseName: headlamp
    namespace: headlamp
    valuesFile: values.yaml
resources:
  - service-account.yaml
  - secret.yaml