apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: argo-cd
    version: 9.4.1
    repo: https://argoproj.github.io/argo-helm
    releaseName: argocd
    namespace: argocd
    valuesFile: values.yaml
    valuesMerge: override
    additionalValuesFiles:
      - overrides.yaml