apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: grafana
    version: 10.5.12
    repo: https://grafana.github.io/helm-charts
    releaseName: grafana
    namespace: grafana
    valuesFile: values.yaml
    valuesMerge: override
    additionalValuesFiles:
      - overrides.yaml
resources:
  - secret.yaml